[options]
addons_path = /mnt/extra-addons
admin_passwd = $pbkdf2-sha512$600000$SynF2HtvjZFyLkUIQSil1A$X9ybSio3/YLks2OAK1DKOwtRO9zMpvHK3gVK0ZRuo7RTW95cw/Sd1t0lPfg2yV5JBba7.tbUwORyJ8FiERlTqw
db_host = postgres_odoo
db_port = 5432
db_user = odoo
db_password = odoo
xmlrpc_port = 8069
list_db = True

